"""Create tables male_players and female_players

Revision ID: 52043467ed87
Revises: 
Create Date: 2023-12-20 14:38:52.874580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52043467ed87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('female_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('playerNumber', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('playerNumber')
    )
    op.create_table('male_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('playerNumber', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('playerNumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('male_players')
    op.drop_table('female_players')
    # ### end Alembic commands ###
